const CategoryFallbackImages = {
    "Art & Creativity": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758525/art-creativity_haqoue.webp",
    "Business & Startups": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/business-startups_ttmtv6.webp",
    "Design": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758526/design_a2mdp7.webp",
    "Default": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778759212/default_h42mr1.webp",
    "Education": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/education_mxhayu.webp",
    "Entertainment": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/entertainment_lso7mk.webp",
    "Environment": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758522/environment_qkzcya.webp",
    "Fashion": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758526/fashion_cbba4b.webp",
    "Finance": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/finance_cr93g3.webp",
    "Food & Cooking": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/food-cooking_vvnpsx.webp",
    "Health & Wellness": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/health-wellness_wnousd.webp",
    "History": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758524/history_rym4rt.webp",
    "Lifestyle": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/lifestyle_xu8jwl.webp",
    "Movies & TV": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/movies-tv_zx19ve.webp",
    "Music": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758522/music_eer0qk.webp",
    "Philosophy": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758524/philosophy_mzbfpt.webp",
    "Politics": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758524/politics_r7wb3l.webp",
    "Productivity": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/productivity_hnicqt.webp",
    "Relationships": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/relationships_xb97xb.webp",
    "Science": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758522/science_h18kx8.webp",
    "Self Improvement": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758521/self-improvement_tcflh1.webp",
    "Society & Culture": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758525/society-culture_lsftah.webp",
    "Sports": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758523/sports_dibd2s.webp",
    "Technology": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/technology_yeby3q.webp",
    "Travel": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758520/technology_yeby3q.webp",
    "Writing & Blogging": "https://res.cloudinary.com/drytkfnwb/image/upload/v1778758526/writing-blogging_hlwl03.webp",
}

export default CategoryFallbackImages